### ISSUE TITLE
Update functionality icons

### ISSUE THREAD

**Issue by mmikaeleriksson** [mmikaeleriksson/workTime#11]
Bus icon is a bed icon right now as bootstrap 3.3.7 did not include a bus icon from glyphicons.

Find some free icons that can be used instead of all current icons, or a bus icon that fits the theme.
Add credits to the creator

**Comment by DilkiSasikala** [comment]
I would like to attempt this...

**Comment by mmikaeleriksson** [comment]
@DilkiSasikala Great, go for it

**Comment by Sweta271097** [comment]
Is the issue still open?

**Comment by mmikaeleriksson** [comment]
Hi @Sweta271097, I haven't gotten any PR yet so go ahead.

**Comment by Shubhayu-Das** [comment]
Hey, can I work on this issue?

**Comment by mmikaeleriksson** [comment]
Hi @Shubhayu-Das, sure go ahead

**Comment by Shubhayu-Das** [comment]
Can I switch glyphicon to fontawesome throughout? Font Awesome is far more extensive and has proper icons too.
