### ISSUE TITLE
Add input pre-texts

### ISSUE THREAD

**Issue by mmikaeleriksson** [mmikaeleriksson/workTime#13]
Work and Lunch input fields have a text in the beginning of the input field.
Do the same for startTime and endTime. 
Perhaps "Start" and "Leave"?

**Comment by xaviersalazar** [comment]
I could take this issue

**Comment by ConnectNitish** [comment]
I would like to take this opportunity.

**Comment by geraldobraz** [comment]
I would like to take this too! Nice project btw!

**Comment by mmikaeleriksson** [comment]
@geraldobraz sure, go ahead :)

**Comment by mmikaeleriksson** [comment]
Solved in #21
