### ISSUE TITLE
Dark/light theme toggle for site

### ISSUE THREAD

**Issue by mmikaeleriksson** [mmikaeleriksson/workTime#14]
I would like to have a toggle for dark/light theme that is saved and loaded in a cookie.
Could add an icon with the other functionality icons

**Comment by mmikaeleriksson** [comment]
Dark mode added in 227141b

**Comment by suleimanbashiru** [comment]
Is this available and how I might I be of help

**Comment by mmikaeleriksson** [comment]
> Is this available and how I might I be of help

Yes this is still available.

I would like a new button next to the existing blue, green and orange buttons where you can toggle dark and light mode.
You can check it out at https://worktime.mikaeleriksson.dev/ for reference

Dark and light mode is currently changed via browser settings:
from css:
@media (prefers-color-scheme: light)
@media (prefers-color-scheme: dark)
