### ISSUE TITLE
Add tab navigation to middle container

### ISSUE THREAD

**Issue by mmikaeleriksson** [mmikaeleriksson/workTime#15]
I would like to add a tab navigation to the top of the container (id: workTimeSection).
Some sort of bootstrap tab that fits the theme of the page (https://www.w3schools.com/bootstrap/bootstrap_tabs_pills.asp)

Two tabs for now, 'Time' and 'Credits' (unless you come up with better names)
The credits tab should include what is written in the credits section of the [readme](https://github.com/mmikaeleriksson/workTime/blob/master/README.md) and then a link to the [github repo.](https://github.com/mmikaeleriksson/workTime)

**Comment by kimi43maro** [comment]
Hey there,

I would be more than happy to help you out over the weekend! Are there any preferences that you have technology-wise how you want this achieved?

**Comment by mmikaeleriksson** [comment]
> Hey there,
> 
> I would be more than happy to help you out over the weekend! Are there any preferences that you have technology-wise how you want this achieved?

Hello. Great, the site uses bootstrap for most ui elements, so that is one thing. Other than that you are free to use what you like.

**Comment by kimi43maro** [comment]
I worked on this over the weekend and I think the solution is pretty much ready, just want to do a bit of refactoring and if you don't mind, do the pull request in October so it counts towards the amazing Hacktoberfest :D

**Comment by mmikaeleriksson** [comment]
@kimi43maro That sounds good, looking forward to seeing it

**Comment by mmikaeleriksson** [comment]
Solved in #30
