### ISSUE TITLE
Make sure input fields are not empty

### ISSUE THREAD

**Issue by mmikaeleriksson** [mmikaeleriksson/workTime#16]
If any of the input fields are set to empty the endTime field becomes NaN:NaN.
So if any input field is empty the value used for that field in the javascript should be set to 0, so that you still get a useable endTime.

**Comment by ConnectNitish** [comment]
I would like to take this change. Is there any refrence so that I can see the textboxes in User Interface which you are referring to.

**Comment by mmikaeleriksson** [comment]
> I would like to take this change. Is there any refrence so that I can see the textboxes in User Interface which you are referring to.

Surely, if you go to the live version https://worktime.mikaeleriksson.dev/
There the three editable input fields are the ones I'm referring to.
The last field which is read only is being incorrectly set to NaN:NaN

**Comment by mmikaeleriksson** [comment]
Solved in #17
