### ISSUE TITLE
Change cookies to localStorage

### ISSUE THREAD

**Issue by mmikaeleriksson** [mmikaeleriksson/workTime#32]
Currently cookies are used to save some values between sessions, the repo js-cookie is added as a submodule as well.
Change the use of cookies to localStorage instead. Remove the submodule js-cookie and references to it in .md files.

**Comment by AlexandreInsua** [comment]
I'd like work in this issue.

**Comment by mmikaeleriksson** [comment]
> I'd like work in this issue.

@AlexandreInsua sure, go ahead :)
