### ISSUE TITLE
Switch between Time worked and Remaining time

### ISSUE THREAD

**Issue by mmikaeleriksson** [mmikaeleriksson/workTime#41]
Right now the counter only counts hours worked. You should be able to choose if you want the counter to count worked or count remaining time.

An equivalent to startCountUp function would have to be added, but count down instead.

**Comment by Nyckel** [comment]
Hi, can i tackle this one ?

**Comment by mmikaeleriksson** [comment]
@Nyckel sure, go ahead :)

**Comment by Nyckel** [comment]
Do you really need another function ? Because getting the remaining time is simple as doing
`let remainingMinutes = workMinutes - countupMinutes`
Also, is the goal adding another FlipClock couting down ? I can add that

**Comment by mmikaeleriksson** [comment]
@Nyckel ok, that works. 
I would like to add the option of choosing count down or count up FlipClock. Maybe a checkbox or something below the FlipClock when it is shown? So there is only one clock, but you can choose what it shows.

**Comment by mmikaeleriksson** [comment]
Fixed in #43
