### ISSUE TITLE
Background problem when page is too long

### ISSUE THREAD

**Issue by mmikaeleriksson** [mmikaeleriksson/workTime#44]
When the page becomes too long by either going into the Credits section or showing the FlipClock and Bus page at the same time, the background repeats it self.

I would like this to be solved by making the background continuously span across the entire page (regardless of height)

![desktopBackground](https://user-images.githubusercontent.com/2462380/67226676-d37adf80-f435-11e9-88e3-f3e2322e48df.PNG)

**Comment by luucashc** [comment]
I do this! Ok?

**Comment by luucashc** [comment]
Ready! Can you accept pull?
