### ISSUE TITLE
Align input fields

### ISSUE THREAD

**Issue by mmikaeleriksson** [mmikaeleriksson/workTime#54]
I would like all the input fields to be aligned, so that they start and end at the same place.
I don't know if bootstrap has any class or feature for this (please look into it)
Otherwise change via css directly.

Red lines showing where all input fields should start/end
![bild](https://user-images.githubusercontent.com/2462380/136061888-f3f74ee2-e67c-49ed-ae1e-36256294c7f2.png)

**Comment by AayushSaini101** [comment]
Please assign this issue

**Comment by mmikaeleriksson** [comment]
> 
> 
> Please assign this issue

Go right ahead and make a PR, as mentioned in the [CONTRIBUTING.md](https://github.com/mmikaeleriksson/workTime/blob/master/CONTRIBUTING.md#pull-request) PRs might not be merged direclty, but I will mark acceptable PRs with the 'hacktoberfest-accepted' label so that it will count
